### ISSUE TITLE
Breaking change in 2.0.1 - only allows uppercase characters

### ISSUE THREAD

**Issue by syserr0r** [gravity00/SimpleISO7064#13]
It should have been made much clearer that version 2.0.1 only allows uppercase characters unlike 1.0.0

I'm not sure if this was intentional or a regression that needs fixing.

**Comment by gravity00** [comment]
@syserr0r you are right and was something I forgot to mention on release notes.

I added a section of relevant changes between version 1 and 2 to the [readme file](https://github.com/gravity00/SimpleISO7064/tree/master?tab=readme-ov-file#v2-vs-v1-notes).

Thank you for the reminder.
