### ISSUE TITLE
Issue with Mod1271Radix36

### ISSUE THREAD

**Issue by robnolletti** [gravity00/SimpleISO7064#9]
I am having an issue where a checksum is not matching what is expected when running this package from NuGet 

Running the source of the function in the package is providing the right checksum however.

https://dotnetfiddle.net/ekXdGO

I am not super familiar with C# so perhaps there is something I am doing wrong here.

**Comment by robnolletti** [comment]
Ah I see, the Nuget package was never updated after this commit.

https://github.com/gravity00/SimpleISO7064/commit/a3b5a6ecca2cf50208fc16cbcce7dccec92b935d

**Comment by gravity00** [comment]
Clearly it was my mistake. I'll release a patch version even today. Thanks for the reminder.

**Comment by MFritsche-XIII** [comment]
I am running into the same bug :(
It would help a lot if you could update the nuget package.

**Comment by gravity00** [comment]
@robnolletti @MFritsche-XIII sorry about the delay.

The project was old and targeted deprecated frameworks, so I had to do a major migration from `xproj+project.json` files to newer VS 2022 `csproj` and had to drop some of the supported frameworks, but unless you are using this on very old mobile devices, it should be fine:

There's a version `2.0.0-rc01` available right now for you to try.
